# Generated by Django 3.1.4 on 2020-12-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]
    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]

